"""Render an evidence file (pytest --evidence) as a docs page.

    .venv/bin/python scripts/evidence_table.py evidence.jsonl docs/evidence.md

One row per validated object; one column per root of trust; each cell
counts the checks that passed (and flags any that failed). Findings and
upstream problems (strict xfails) are listed separately.
"""

import collections
import json
import sys

from evidence import ROOTS

STRONG = [r for r in ROOTS if r != "self-consistency"]


def main(src, dst):
    lines = [json.loads(line) for line in open(src)]
    run, tests = lines[0], lines[1:]
    cells = collections.defaultdict(lambda: collections.Counter())
    issues = []
    for t in tests:
        if t["kind"] in ("finding", "upstream"):
            issues.append(t)
            continue
        for obj in t["objects"]:
            for root in t["roots"]:
                cells[(obj, root)][t["outcome"]] += 1
    objects = sorted({o for o, _ in cells}, key=lambda o: (not o.startswith("virgil"), o))
    roots = [r for r in STRONG + ["self-consistency"] if any((o, r) in cells for o in objects)]
    roots += sorted({r for _, r in cells} - set(roots))

    def cell(c):
        if not c:
            return ""
        bad = c["failed"] + c["xpassed"] + c["error"]
        good = c["passed"] + c["xfailed"]
        return (f"✗ {bad} failed, " if bad else "") + f"✓ {good}"

    v = run["virgil"]
    out = [
        "# Evidence",
        "",
        "<!-- Generated by scripts/evidence_table.py from a pytest --evidence run. -->",
        "",
        f"Run {run['date']} ({run['runner']}) against virgil {v['version']} at "
        f"`{(v['commit'] or 'unknown')[:10]}`, virgil-validation at "
        f"`{(run['validation_commit'] or 'unknown')[:10]}`.",
        "Packages: " + ", ".join(f"{k} {val}" for k, val in run["versions"].items() if val) + ".",
        "",
        "Each cell counts the tests that check the object against that root of",
        "trust (see [design](design.md)); negative controls and checks of our own",
        "references are included under the object they concern.",
        "",
        "| object | " + " | ".join(roots) + " |",
        "| --- | " + " | ".join("---" for _ in roots) + " |",
    ]
    for o in objects:
        out.append(f"| `{o}` | " + " | ".join(cell(cells.get((o, r))) for r in roots) + " |")
    out += ["", "## Known problems (strict xfails)", "", "| kind | object | test | outcome |", "| --- | --- | --- | --- |"]
    for t in issues:
        out.append(f"| {t['kind']} | {', '.join(f'`{o}`' for o in t['objects'])} | `{t['test'].split('::', 1)[1]}` | {t['outcome']} |")
    out.append("")
    with open(dst, "w") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main(*sys.argv[1:3])
